# Fluid Attacks SCA Scanner Configuration for WackoPicko
namespace: wackopicko
output:
  file_path: /app/sca-results.csv
  format: CSV
working_dir: /app
language: EN
strict: true

sca:
  include:
    - .
  exclude:
    - glob(**/upload/**)
