# Fluid Attacks Scanner Configuration for WackoPicko
namespace: wackopicko
output:
  file_path: ./scan-results.csv
  format: CSV
working_dir: .
language: EN

sast:
  include:
  - .
  exclude:
  - glob(**/upload/**)
  - glob(**/node_modules/**)

sca:
  include:
  - .
  exclude:
  - glob(**/upload/**)
